[workspace]
members = [
  "jormungandr-lib",
  "jormungandr-watchdog",
  "jormungandr",
  "jcli",
  "jormungandr-integration-tests",
  "jormungandr-scenario-tests",
]

exclude = [
    "chain-deps",
]
